trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: TerraformInstaller@0
  displayName: 'Terraform Install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure-SC'
    backendAzureRmResourceGroupName: 'Test'
    backendAzureRmStorageAccountName: 'demostorageaccount'
    backendAzureRmContainerName: 'terraformbackend'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV3@3
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV3@3
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure-SC'
- task: TerraformTaskV3@3
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Azure-SC'
