prefix = "Terraform"
username = "admin"
password = "insecurepassword"
location = "west europe"
resource_group = "Test"
storage_account = "demostorageaccount"
container_name = "terraformbackend"
address_space_vnet = ["10.0.0.0/16"]
address_space_subnet = ["10.0.2.0/24"]
size = "Standard_F2"
